spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - local
    
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
